### ISSUE TITLE
What is the difference between this library and RN Switch

### ISSUE THREAD

**Issue by elisechant** [thousight/react-native-draggable-switch#42]
Hi there, just curious what the key difference is between your library and [React Native Switch](https://reactnative.dev/docs/switch)?

**Comment by thousight** [comment]
This one is built completely with RN XML while the React Native Switch is using the native switch component with native switch style. So React Native Switch has a different look in iOS and Android while mine is consistently the same. Also, mine allows users to drag around while the native one doesn't necessarily do that.
